# Generated by Django 4.2.3 on 2023-08-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_order_cms_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cms_css',
            field=models.CharField(default='-', max_length=200, null=True, verbose_name='CSS класс'),
        ),
    ]
