# Generated by Django 4.2.3 on 2023-08-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_order_cms_css'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cms_css',
        ),
    ]
